FROM maven:4.0.0-openjdk-17-slim AS build

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package

FROM adoptopenjdk:17-jdk-hotspot-bionic-slim

COPY --from=build /app/target/taxislibres.jeffrey-*.jar /app/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/app.jar"]